//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARMETRO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class area_estacionamiento
    {
        public area_estacionamiento()
        {
            this.area_estacionamiento_pagos = new HashSet<area_estacionamiento_pagos>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public int posicion { get; set; }
        public int id_piso { get; set; }
        public int id_vehiculo { get; set; }
        public System.DateTime hora_entrada { get; set; }
        public System.DateTime hora_salida { get; set; }
        public decimal total_facturado { get; set; }
    
        public virtual ICollection<area_estacionamiento_pagos> area_estacionamiento_pagos { get; set; }
        public virtual piso piso { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
