//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARMETRO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class area_estacionamiento_pagos
    {
        public int id_pago { get; set; }
        public int id_area_estacionamiento { get; set; }
        public string descripcion_pago { get; set; }
        public decimal valor_facturado { get; set; }
    
        public virtual area_estacionamiento area_estacionamiento { get; set; }
    }
}
