//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARMETRO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class piso
    {
        public piso()
        {
            this.area_estacionamiento = new HashSet<area_estacionamiento>();
        }
    
        public int id { get; set; }
        public Nullable<int> numero { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<area_estacionamiento> area_estacionamiento { get; set; }
    }
}
