//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARMETRO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class propietario
    {
        public propietario()
        {
            this.vehiculoes = new HashSet<vehiculo>();
        }
    
        public int id { get; set; }
        public string cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<vehiculo> vehiculoes { get; set; }
    }
}
