//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARMETRO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public vehiculo()
        {
            this.area_estacionamiento = new HashSet<area_estacionamiento>();
        }
    
        public int id { get; set; }
        public string placa { get; set; }
        public string color { get; set; }
        public string marca { get; set; }
        public int id_propietario { get; set; }
    
        public virtual ICollection<area_estacionamiento> area_estacionamiento { get; set; }
        public virtual propietario propietario { get; set; }
    }
}
